### ISSUE TITLE
node-sonos-http-api got an update and now Module doesnt work

### ISSUE THREAD

**Issue by dinkybluebug** [CFenner/MagicMirror-Sonos-Module#11]
node-sonos-http-api got an update to accomodate node v6.x and now the module doesnt display any track information.

The module displays speaker/room name but no track or artist name or album art.

Any ideas why this might be?

Marc

**Comment by pixelecho** [comment]
same problemsame node version any solutions?

**Comment by CFenner** [comment]
Hey guys, need to do some research here.. no idea. Have the same problem currently..

**Comment by pixelecho** [comment]
I found the bug problem is solved when replace line number 35 in sonos.js to

`var state = item.coordinator.state.playbackState; // `

**Comment by dinkybluebug** [comment]
So my sonos.js looks like this now

```
	render: function(data){
		var text = '';
		$.each(data, function (i, item) {
			var room = item.coordinator.roomName;
			var state = item.coordinator.state.playbackState; //
			var artist = item.coordinator.state.currentTrack.artist;
			var track = item.coordinator.state.currentTrack.title;
			var cover = item.coordinator.state.currentTrack.absoluteAlbumArtURI;
			var streamInfo = item.coordinator.state.currentTrack.streamInfo;
			if(item.members.length > 1){
				room = '';
				$.each(item.members, function (j, member) {
```
this isnt working for me.

instead my mirror now shows this image :  [click here for image](https://s11.postimg.org/zat7uy9lf/IMG_4315.jpg)

**Comment by Sillec123** [comment]
Hello, 
i have the same issue. The module only shows the room names. If i change the line 35 in the sonos.js i see no picture but i get the album and artist info.

**Comment by skpy** [comment]
I hate to pile on, but I have nothing more to add than "me too!".  If I modify line 35 as described above, I get only a list of zone names.  Interestingly, if I leave lined 35 unmodified I get the same output: simply a list of zone names.

**Comment by CFenner** [comment]
@dinkybluebug @pixelecho @Sillec123 @skpy sorry for the delay, it should work now.
