### ISSUE TITLE
Clearify installation of node-sonos-http-api

### ISSUE THREAD

**Issue by magicsunday** [CFenner/MagicMirror-Sonos-Module#17]
Hi, could you please clearify the installation of the module and the sonos http api?

The following I tried:

```
cd ~
cd MagicMirror/
cd node_modules/
wget https://github.com/jishi/node-sonos-http-api/archive/master.zip
unzip master.zip
npm install --production
npm start
```

(?) How to autostart the sonos api?
(?) My MagicMirror wont show up the Sonos Module. The screen keeps blank.

**Comment by dinkybluebug** [comment]
I created a bash script that did npm start. And then used pm2 start nameofbash.sh

**Comment by CFenner** [comment]
pm2 is really great. The usage is described on the magic mirror page.

**Comment by magicsunday** [comment]
I finally get the sonos api to work:

cd ~
cd MagicMirror
npm install --production jishi/node-sonos-http-api
cd ~/MagicMirror/node_modules/sonos-http-api
pm2 start server.js -x --name "http-api"
pm2 dump
