### ISSUE TITLE
Neverending "Loading music ..." on MM²

### ISSUE THREAD

**Issue by djsunrise19** [CFenner/MagicMirror-Sonos-Module#3]
Sonos API installed and started (works fine):
![sonos](https://cloud.githubusercontent.com/assets/14234570/14560360/952fa21c-030f-11e6-88a2-446ac3f102aa.jpg)

Made config entry:
![sonosconfig](https://cloud.githubusercontent.com/assets/14234570/14560369/ab064384-030f-11e6-884e-718d52f5f6f1.jpg)

sonos folder in modules (no subfolder). But:
![sonosload](https://cloud.githubusercontent.com/assets/14234570/14560507/8d45945c-0310-11e6-8f49-3fa819ba7520.jpg)

Console:
![console](https://cloud.githubusercontent.com/assets/14234570/14560510/9223750c-0310-11e6-8a67-234d111d226f.jpg)

Edit: I also checked the KnownIssue and restart the service / raspi.

**Comment by CFenner** [comment]
Is this the console on your Pi or a remote call? If it's remote a call to "localhost" won't work. 
Nevertheless currently I've the same problem. I'll have a look into it tonight ;)

**Comment by djsunrise19** [comment]
Okay :)

**Comment by djsunrise19** [comment]
Hi! Any news?

**Comment by CFenner** [comment]
I have a look at it now :)

**Comment by CFenner** [comment]
hm.. it's working on my laptop, did you try to restart the service/mirror?

**Comment by djsunrise19** [comment]
Yes, many times. sonos api is working, but module doesn't load. You said you had the same problem?

**Comment by CFenner** [comment]
..weired. I should definetly rewrite the module to use a backend handler..

**Comment by CFenner** [comment]
Do you use the IP address or localhost?

**Comment by CFenner** [comment]
The issue for me was, that I set apiBase to '192.168.x.x' and missed the '//' in front, '//192.168.x.x' is needed.

**Comment by djsunrise19** [comment]
> Do you use the IP address or localhost?

What do you mean? The "Loading music..." is on my raspi, no remote.

**Comment by CFenner** [comment]
You can configure the sonosAPI host via the module config:
<img width="389" alt="bildschirmfoto 2016-04-19 um 23 17 30" src="https://cloud.githubusercontent.com/assets/9592452/14655954/234f95c0-0685-11e6-965d-4df0756972ce.png">

Can you try to set the apiBase to your Pi's IP and open the mirrors interface from your computer. 
What's in your browsers console now?

**Comment by djsunrise19** [comment]
Okay, I made the edit in the config file but it doesn't help. Still the same on raspi.

Browser console:
![sonosneu](https://cloud.githubusercontent.com/assets/14234570/14656131/14b61b0a-0686-11e6-9b7d-128814627b74.jpg)

**Comment by CFenner** [comment]
Could you update the sonos module, just pushed some changes. The log says you try to connect to localhost, not the Pi's IP. Did you restart the mirror?

**Comment by djsunrise19** [comment]
Yes, I made a restart and updated the module. Still the same, hmmm.

**Comment by CFenner** [comment]
still the same console messages?

**Comment by djsunrise19** [comment]
![sonos2004](https://cloud.githubusercontent.com/assets/14234570/14688325/54df0388-0742-11e6-86b6-fdcab2642973.jpg)

**Comment by CFenner** [comment]
Could you fetch the newest sources?

**Comment by djsunrise19** [comment]
Great, with the new update everything works fine :)

**Comment by CFenner** [comment]
Feel free to create new issues if any problems occur. Especially multi room, I just have one speaker.
