### ISSUE TITLE
Loading music... local browser

### ISSUE THREAD

**Issue by darkeagl** [CFenner/MagicMirror-Sonos-Module#5]
Hi,

when I open the mirror url on a different machine I get the Sonos Infos, but when I look at the hdmi connected one to my raspberry it just stays Loading music... and doesnt change.

I am using a Pi B+ with Epiphany in Kiosk mode.

Any help would be apreciated.

I just found this error I am getting:
 Message: console message: http://localhost:8080/modules/sonos//sonos.js @101: TypeError: undefined is not a function (evaluating 'this.data.position.endsWith("left")')

**Comment by CFenner** [comment]
what is the config for the module?

**Comment by CFenner** [comment]
The error is in the part where the module position is analyzed. The error occurs because the position is not a string. Is it set?

**Comment by darkeagl** [comment]
Bottom_right and only show play room. It works on a PC when I call the site
with 192.x.x.x:8080 only on the local pi b+ it stays on "loading music..."
and won't show anything but the other modules

**Comment by CFenner** [comment]
Could you please post the config, could there be an error in the config?
The modules are rendered client side, so maybe your remote browser is a bit more forgiving the the pi's one.

**Comment by darkeagl** [comment]
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 */

var config = {
port: 8080,

language: 'de',
timeFormat: 24,
units: 'metric',

modules: [
{
module: 'alert',
},
{
module: 'clock',
position: 'top_left'
},
{
module: 'calendar',
header: 'DE Holidays',
position: 'top_left',
config: {
calendars: [
{
symbol: 'calendar-check-o ',
url: 'webcal://www.calendarlabs.com/templates/ical/Germany-Holidays.ics'
}
]
}
},
{
module: 'compliments',
position: 'lower_third'
},
{
module: 'currentweather',
position: 'top_right',
config: {
location: 'Munich',
appid: '61c22dd8f39ef1e119d6e615e0e023c0',
updateInterval: '1800000'
}
},
{
module: 'weatherforecast',
position: 'top_right',
header: 'Weather Forecast',
config: {
          location: 'Munich',
            appid: '61c22dd8f39ef1e119d6e615e0e023c0'
}
},
{
module: 'newsfeed',
position: 'bottom_bar',
config: {
feeds: [
{
title: "New York Times",
url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
}
],
showSourceTitle: true,
showPublishDate: true
}
},
{
module: 'sonos',
position: 'bottom_right',
config: {
showStoppedRoom: false,
          showRoomName: true,
showAlbumArt: true
}
},

]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}

-----

Lorand G

**Comment by darkeagl** [comment]
Hi,

I tried a couple of browsers on the pi (kweb, epiphany, iceweasel) and none could display the Sonos stuff just "Loading Music" if I open it remotely on a other machine everything displays fine. Please help, I would really like to use the sonos module.

**Comment by CFenner** [comment]
I have a look at it tomorrow.

**Comment by CFenner** [comment]
@darkeagl can you Display a Browser Console on The PI?

**Comment by darkeagl** [comment]
What do you mean by browser console? I can open what you need but Chromium, because that cant run on Pi 1B+

**Comment by CFenner** [comment]
In a normal browser you can open an error console. This sounds like a browser problem, so it would be interesting to know what the browser doesn't like. I don't know how to do this in chromium or any other PI browser.
