### ISSUE TITLE
Music doesn't display on RPI1

### ISSUE THREAD

**Issue by benjeefox** [CFenner/MagicMirror-Sonos-Module#6]
Hi,
I'm using a RPI2 with MM2 as server only
I'm using a RPI1 to display MM2 screen, but Sonos module does not display any data on it, only Loading Music while IT is displayed correctly on a browser (on a Windows)
Any idea ?

**Comment by CFenner** [comment]
Which browser do you use?

**Comment by benjeefox** [comment]
Well, Chromium, this RPI1 was the one used for my Magic Mirror One

**Comment by CFenner** [comment]
Hm, no idea, I also don't know how to debug chromium. Do you know how to get the console output?

**Comment by benjeefox** [comment]
not really.... :)
